[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.envs]
NODE_ENV = "production"
PORT = "5000" 